### ISSUE TITLE
Feature request:  Log bombs

### ISSUE THREAD

**Issue by irobot73** [game-servers/pz-mod-log-extender#2]
I might have been blind, so excuse if I missed it perusing your code-base.  I'd like to see if I could request a feature to track bombs (Molotov+):  Created, equipped, (& most importantly) utilized.  I've got a bit of an issue on my dedi w/ pyros attempting to burn down as much as any city they can spawn into & would love to be able to (more) easily track 'em down so they can be properly banned.

Otherwise, looks like a decent addition to servers.  Keep up the good work.

**Comment by outdead** [comment]
Hi! Thanks for your issue. There are some log of bombs usage in map.txt files. This is not part of my mod, this is part of the vanilla game. You can find them with terminal command
```bash
$ grep --include=*_map.txt -Er "Molotov|Bomb" ~/Zomboid/Logs

Zomboid/Logs/logs_21-12/21-12-21_00-02-37_map.txt: [28-12-21 20:15:04.165] 76561198300000001 "Player1" added Base.SmokeBomb at 13592,5820,0.
Zomboid/Logs/logs_21-12/21-12-21_00-02-37_map.txt: [21-12-21 21:35:57.898]76561198300000001 "Player1" added Base.Molotov at 13965,3233,0.
```

As for the creation of bombs, I plan to add logging of all crafting and bombs will be there too. But I will start this next year, now I have slightly different priorities.

**Comment by irobot73** [comment]
I appreciate you keeping it on the back-burner.

Can't wait to see what's next.  Any road map available?

**Comment by outdead** [comment]
In near future I want to:
1. Fix PVP hit logs. Sometimes mod writes hit user logs when player is already dead. 
2. Add Logs for Brush Tool usage.
3. Add Logs for vehicles spawn/remove.
4. Add Alternative logs of destroying buildings.
5. Add Logs for crafting.
6. Add Logs for traps usage.

**Comment by outdead** [comment]
Hi! I updated the mod. Try [v0.11.0](https://github.com/openzomboid/log-extender/releases/tag/v0.11.0) version. There are `_craft.txt` files with such records:
```
[13-12-22 05:36:01.687] 76561198300000001 "Player1" crafted 1 Base.Molotov with recipe "Make Molotov Cocktail" (10483,12741,0).
```

**Comment by irobot73** [comment]
Thanks.  Got it installed & seeing what it can do.  I see if logged where I gave myself a few molly's...no so much in their utilization (taking out a small zed mob)

Is the PLAYER log supposed to update (looks like) every ~3 min?

![Screenshot from 2022-12-13 14-07-56](https://user-images.githubusercontent.com/7168597/207423307-4de233f3-e512-4877-87e1-f89bf2ea8529.png)

**Comment by outdead** [comment]
Yes, Players "tick" record writes every 1 in game hour. I added this for possibility to create external logs parser that uses this information and saves in database. It helps to catch cheaters, to create players statistics. You can turn this log off in sandbox variables: change `PlayerTick` to false.
```
    LogExtender = {
        PlayerConnected = true,
        PlayerLevelup = true,
        PlayerTick = true, 
        VehicleEnter = true,
        VehicleExit = true,
        VehicleAttach = true,
        VehicleDetach = true,
        TimedActions = true,
        TakeSafeHouse = true,
        ChangeSafeHouseOwner = true,
        ReleaseSafeHouse = true,
        RemovePlayerFromSafehouse = true,
        SendSafeHouseInvite = true,
        JoinToSafehouse = true,
        HitPVP = true,
        AdminManageItem = true,
        AdminTeleport = true,
        AlternativeMap = true,
    },
```

**Comment by irobot73** [comment]
Long as I know the expectations, I'm all good.  Thanks again.
