### ISSUE TITLE
Request: Log weapon equipped

### ISSUE THREAD

**Issue by Lu5ck** [game-servers/pz-mod-log-extender#3]
Would be nice if able to log specific type of weapons equipped. Currently Brita mod and some people using certain weapon to grief on my server.

**Comment by outdead** [comment]
Hi! Do you mean the fast equip panel?

**Comment by Lu5ck** [comment]
Active weapon

**Comment by outdead** [comment]
I don't understand your request. Can you write in more detail?

**Comment by Lu5ck** [comment]
Erm.

When the player equipped a weapon, on the hand, log the type of weapon equipped, including the time and location. Preferably able to specific the type of weapon to log.

**Comment by outdead** [comment]
I don't see why this is necessary.

**Comment by Lu5ck** [comment]
So we can see who is griefing with certain type of weapons. There are weapons like molotov that create big aoe damage.

**Comment by outdead** [comment]
But we already have this in `*_map.txt` logs:
```
[19-12-22 00:51:49.123] 76561198960000001 "Player1" added Base.Molotov at 12866,1519,0.
[26-12-22 11:58:48.961] 76561198960000002 "Player2" destroyed Door with Base.ClubHammer at 6142,9406,0.
```

**Comment by Lu5ck** [comment]
Yes, that is for vanilla. I am asking if possible for non-vanilla items.

**Comment by darrensapalo** [comment]
> But we already have this in `*_map.txt` logs:
> 
> ```
> [19-12-22 00:51:49.123] 76561198960000001 "Player1" added Base.Molotov at 12866,1519,0.
> [26-12-22 11:58:48.961] 76561198960000002 "Player2" destroyed Door with Base.ClubHammer at 6142,9406,0.
> ```

Hi @outdead , does this work as well with when weapons are used to break glass windows of vehicles?

**Comment by outdead** [comment]
No. It writes to `*_cmd.txt` logs. There are no information about weapon
```
[05-02-23 02:27:47.671] 76561198960000001 "Player1" vehicle.damageWindow @ 6490,9329,0.
```
