### ISSUE TITLE
Как узнать по этим логам, входил ли человек с одного ПК но с разных steamId.

### ISSUE THREAD

**Issue by Scinetnisou** [game-servers/pz-mod-log-extender#4]
По этим логам можно определить, что человек заходит с нескольких аккаунтов steam под разными пользователями? Хочу предусмотреть возможность блокировки создания твинков.

**Comment by outdead** [comment]
Можно, но сам мод здесь не при чем. Можно делать grep по логу `*_user.txt` и выбрать все steamID с которых юзер что-то делал.
```
grep --include=*_user.txt -rh username ~/Zomboid/Logs/ | grep -oE "[0-9]{17}" | sort -u
```
где username это проверяемый игрок. Если будет выведено более одного стима, то искомый нарушитель найден.

**Comment by Scinetnisou** [comment]
А если у пользователя на каждый steam аккаунт свой созданный персонаж?
В таком случае username и steamid всегда будут уникальны. Нет возможности определить, что у пользователя несколько аккаунтов стим под разными персонажами?

**Comment by outdead** [comment]
Может быть по ip смотреть. Он пишется в лог `DebugLog-server.txt`.
